/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package direccionred;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author manuel
 */
public class ipJFrame extends javax.swing.JFrame {
   
    /**
     * Creates new form ipJFrame
     */
    public ipJFrame() {
        
        initComponents();
    }
    final JPanel panel = new JPanel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        direccionIP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        subred = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        panelResultado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        clase = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Direccion IP:");

        direccionIP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                direccionIPMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                direccionIPMouseExited(evt);
            }
        });

        jLabel2.setText("Mascara de subred:");

        jLabel3.setText("Direccion de Red: ");

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Clase: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clase, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelar))
                            .addComponent(direccionIP)
                            .addComponent(subred)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelResultado))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(direccionIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(subred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(cancelar)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        direccionIP.setText("");
        subred.setText("");
        panelResultado.setText("");
        panelResultado.setEditable(false);
        clase.setText("");
    }//GEN-LAST:event_cancelarActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        try{
            panelResultado.setEditable(false);
            clase.setEditable(false);
            String ip = direccionIP.getText();
            DireccionRed r1 = new DireccionRed(ip);   
            String[] arreglo = r1.contarOctetos(ip);
            int[] octeto=new int[4];
            int[] octetoBin = new int[4];
            for(int i=0; i< arreglo.length;i++){
                octeto[i] = Integer.parseInt(arreglo[i]);//Convertir a enteros los 4 octetos
                octetoBin[i] = r1.toBinario(octeto[i]);//Convertir a binario los 4 octetos
            }
            int ipint = octeto[0];//Clasificar las redes por clases
            //RESTRICCIONES
            if(ipint==127){//No se puede porque está reservada
                JOptionPane.showMessageDialog(panel, "La direccion 127 está reservada", "Error", JOptionPane.ERROR_MESSAGE);
                direccionIP.setText("");
                subred.setText("");
                panelResultado.setText("");
            }else if(ipint == 0){
                JOptionPane.showMessageDialog(panel, "La direccion 0 está reservada", "Error", JOptionPane.ERROR_MESSAGE);
                direccionIP.setText("");
                subred.setText("");
                panelResultado.setText("");
            }else if(ipint == 255){
                JOptionPane.showMessageDialog(panel, "La direccion 255 está reservada", "Error", JOptionPane.ERROR_MESSAGE);
                direccionIP.setText("");
                subred.setText("");
                panelResultado.setText("");
            }else{
                //ASIGNACIONES
                if(ipint<127){
                    r1.setClase("A");
                    if(subred.getText().equals("")){
                        r1.setMascara("255.0.0.0");
                        subred.setText(r1.getMascara());
                    }else
                        r1.setMascara(subred.getText());
                }else if(ipint>127 && ipint<=191){
                    r1.setClase("B");
                    if(subred.getText().equals("")){
                        r1.setMascara("255.255.0.0");
                        subred.setText(r1.getMascara());
                    }else
                      r1.setMascara(subred.getText());
                }else if(ipint>191 && ipint<225){
                    r1.setClase("C");
                    if(subred.getText().equals("")){
                        r1.setMascara("255.255.255.0");
                        subred.setText(r1.getMascara());
                    }
                    else
                        r1.setMascara(subred.getText());
                }
            }
            
            clase.setText(r1.getClase());
            panelResultado.setText("");
            for(int i=0; i< arreglo.length;i++){
                panelResultado.setText(panelResultado.getText()+Integer.parseInt(r1.direcciondeRed()[i],2)+".");
            }
        }catch(Exception e){
              JOptionPane.showMessageDialog(panel, "Ingrese una direccion IP valida", "Error", JOptionPane.ERROR_MESSAGE);  
        }
       
    }//GEN-LAST:event_aceptarActionPerformed

    private void direccionIPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_direccionIPMouseClicked
        // TODO add your handling code here:
        subred.setText("");
        clase.setText("");
        panelResultado.setText("");
    }//GEN-LAST:event_direccionIPMouseClicked

    private void direccionIPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_direccionIPMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionIPMouseExited


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ipJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ipJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ipJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ipJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ipJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField clase;
    private javax.swing.JTextField direccionIP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField panelResultado;
    private javax.swing.JTextField subred;
    // End of variables declaration//GEN-END:variables
}
